development:
  adapter: postgresql
  encoding: utf8
  database: showdown_development
  pool: 5
  host: localhost
test:
  adapter: postgresql
  encoding: utf8
  database: showdown_test
  pool: 5
  host: localhost
production:
  adapter: postgresql
  encoding: utf8
  database: showdown_production
  pool: 5
  host: localhost